name: Portfolio Tracker

on:
  schedule:
    - cron: '30 7 * * *'  # 1 PM IST
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  track-portfolio:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run portfolio tracker
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        RETURN_THRESHOLD: ${{ vars.RETURN_THRESHOLD }}
      run: python main.py
